#!/usr/bin/env python3
# coding=utf-8

import turtle

# (1) --- Фронатальная сторона коробки ---
# Начинаем окрашивать фронатальную сторону коробки
turtle.fillcolor("#FFFF00")
turtle.pencolor('#555555')
turtle.begin_fill()

# Начинаем построение фронатальной стороны коробки
turtle.left(155)
turtle.forward(150)
turtle.left(60)
turtle.circle(15, 60)
turtle.left(60)
turtle.forward(150)
turtle.left(120)
turtle.circle(-15, 60)
turtle.end_fill()
turtle.right(90)
turtle.forward(15)
turtle.right(120)
turtle.forward(15)

turtle.penup()
turtle.right(30)
turtle.forward(80)
turtle.right(90)
turtle.forward(10)
turtle.left(90)
turtle.pensize(2)
turtle.pencolor('#0000FF')
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(10)

turtle.pensize(1)
turtle.penup()
turtle.forward(18)
turtle.right(90)
turtle.forward(5)
turtle.left(90)
turtle.left(60)
turtle.pendown()
turtle.fillcolor('#0000FF')
turtle.begin_fill()
turtle.circle(15, 60)
turtle.right(120)
turtle.forward(3)
turtle.right(60)
turtle.circle(-15, 60)
turtle.end_fill()

turtle.penup()
turtle.left(120)
turtle.forward(8)
turtle.left(60)
turtle.pendown()
turtle.begin_fill()
turtle.circle(15, 60)
turtle.right(120)
turtle.forward(3)
turtle.right(60)
turtle.circle(-15, 60)
turtle.end_fill()

turtle.fillcolor('#FF0000')
turtle.pencolor('#000000')
turtle.left(180)
turtle.begin_fill()
turtle.circle(15, 60)
turtle.right(120)
turtle.forward(6)
turtle.right(60)
turtle.circle(-15, 60)
turtle.right(60)
turtle.forward(6)
turtle.end_fill()

turtle.penup()
turtle.back(6)
turtle.right(90)
turtle.forward(15)
turtle.left(90)
turtle.pendown()
turtle.forward(156)
turtle.left(30)
turtle.forward(15)

turtle.done()
